### ISSUE TITLE
Do not abuse "posiadać"

### ISSUE THREAD

**Issue by splewako** [aviarypl/team#1]
- http://wittamina.pl/posiadac-czy-miec/
- https://pl.wiktionary.org/wiki/posiada%C4%87

**Comment by splewako** [comment]
https://github.com/aviarypl/mozilla-l10n-central-pl/commit/344358a4fc3bb62d979aad712dc3eeed8809a81c

**Comment by splewako** [comment]
@adrianer, it would be good to also change this in [mailViewHasAttachments](https://github.com/aviarypl/mozilla-l10n-central-pl/blame/branches/default/tip/suite/chrome/mailnews/mailviews.properties) in SeaMonkey

**Comment by splewako** [comment]
[Firefox OS](https://transvision.mozfr.org/?recherche=posi&repo=gaia&sourcelocale=pl&locale=pl&search_type=strings) and [websites](https://transvision.mozfr.org/?recherche=posi&repo=mozilla_org&sourcelocale=pl&locale=pl&search_type=strings) also need some fixes

**Comment by adrianer** [comment]
Thx, fixed for suite: https://hg.mozilla.org/l10n-central/pl/rev/c90bfdde4713 https://hg.mozilla.org/l10n-central/pl/rev/508773bec768

**Comment by splewako** [comment]
I think we can close this one now.
