### ISSUE TITLE
Paste is translated as kopiuj in Firefox for Andorid

### ISSUE THREAD

**Issue by halamix2** [aviarypl/team#13]
When you long tap on address bar you can see 4 options, 2nd one has wrong translation

**Comment by piotrdrag** [comment]
Thank you very much! I've fixed it in central, which will be Firefox 52. I'll see about backporting it to other channels, so the fix gets to users earlier.

**Comment by piotrdrag** [comment]
@splewako pushed the fix to aurora, so it will be in Firefox 51: https://hg.mozilla.org/releases/l10n/mozilla-aurora/pl/rev/339f79766251
