### ISSUE TITLE
Don't use "Ci"/"Cię" (and possibly "Ciebie")

### ISSUE THREAD

**Issue by splewako** [aviarypl/team#16]
Not new, but to have a place to reference.

As a general rule, don't use "Ci", "Cię" (and possibly "Ciebie") - these could be possibly removed or replaced with "Tobie" or "Ciebie".

- [Bug 2224 - Pozbyć się zaimka "Cię/Ciebie"](http://attic.aviary.pl/pl.aviary.bugs/show_bug.cgi%3Fid=2224.html)
- https://github.com/aviarypl/mozilla-l10n-pl/commit/75e0e79ce62a56040b4cc95540fd10fe82107723
- https://github.com/aviarypl/mozilla-l10n-pl/commit/8cabd7c1f21bb91f329e2dba0e170cf7c35f89ad
- https://github.com/aviarypl/mozilla-l10n-pl/commit/43d33424c8ad336c8994d4e7c374c84369b1864a
- https://github.com/mozilla-l10n/www.mozilla.org/commit/e2866d3a0197773117d5261233a97c7bccfba89e

**Comment by piotrdrag** [comment]
Na pewno powinniśmy wszędzie pozbywać się "Cię"? W wielu zdaniach "Ciebie" brzmi nienaturalnie: "Zapisz się na newsletter Mozilli, aby być na bieżąco z problemami, które Ciebie dotykają."

**Comment by splewako** [comment]
> Na pewno powinniśmy wszędzie pozbywać się "Cię"? W wielu zdaniach "Ciebie" brzmi nienaturalnie: "Zapisz się na newsletter Mozilli, aby być na bieżąco z problemami, które Ciebie dotykają."

Na pewno, "Ciebie" w miarę możliwości również ale przede wszystkim "Ci", "Cię". W przytoczonym zdaniu obie wersje źle się czytają, zmiana końcówki na "Ciebie dotyczą" pewnie by pomogła ale to zdanie wymaga również innych korekt.
