### ISSUE TITLE
Unify "learn more" translations

### ISSUE THREAD

**Issue by splewako** [aviarypl/team#2]
Unify "learn more" translations, especially "Dowiedz się więcej (o …)" and "Więcej informacji (o …)" especially when they are not only small part of a sentence, like in various links and buttons.

[Firefox OS](https://transvision.mozfr.org/?recherche=learn+more&repo=gaia&sourcelocale=en-US&locale=pl&search_type=strings), [websites](https://transvision.mozfr.org/?recherche=learn+more&repo=mozilla_org&sourcelocale=en-US&locale=pl&search_type=strings) and [SeaMonkey](https://github.com/aviarypl/mozilla-l10n-central-pl/blame/branches/default/tip/suite/chrome/common/notification.dtd) (@adrianer)

**Comment by adrianer** [comment]
thx, fixed for suite: https://hg.mozilla.org/l10n-central/pl/rev/81f5aed1bb1c

**Comment by piotrdrag** [comment]
Fixed on websites: https://github.com/mozilla-l10n/www.mozilla.org/commit/0590a92a3b8f0c5be1c00d08ea82b19ecce67353

**Comment by splewako** [comment]
I think we could close this one.
