### ISSUE TITLE
Polski słownik poprawnej pisowni - przestał działać w nowszej wersji TB 60.0b2 (32-bit)

### ISSUE THREAD

**Issue by mavidill** [aviarypl/team#20]
Polski słownik poprawnej pisowni - przestał działać w nowszej wersji TB 60.0b2 (32-bit)
"Polski słownik poprawnej pisowni could not be installed because it is not compatible with Thunderbird 60.0"

**Comment by splewako** [comment]
Ten dodatek niestety nie jest zarządzany przez [zespół Aviary.pl](http://www.aviary.pl) i zasadniczo najlepiej się kontaktować z osobami nim zarządzającymi (poprzez witrynę [addons.mozilla.org](https://addons.mozilla.org/pl/thunderbird/addon/polish-spellchecker-dictionary/)).

W spolszczonych wydaniach słownik jest domyślnie i powinien zawsze działać. Natomiast wersja 60 to [obecnie beta](https://www.mozilla.org/pl/thunderbird/channel/) a w [informacjach o wydaniu](https://www.mozilla.org/en-US/thunderbird/60.0beta/releasenotes/) można znaleźć coś takiego:
> IMPORTANT: Add-ons not marked as compatible with Thunderbird 60 by their authors will be disabled (this can be reverted via preference extensions.strictCompatibility)

**Comment by splewako** [comment]
Zakładam, że powyższe informacje rozwiązały problem.
