### ISSUE TITLE
Replace "ponieważ" with "gdyż"

### ISSUE THREAD

**Issue by splewako** [aviarypl/team#6]
Let's consider replacing occurrences of "ponieważ" with "gdyż" mainly for it's shorter presentation which should help us fit especially on mobile and websites more easily.

**Comment by piotrdrag** [comment]
I don't like that change. "Ponieważ" seems to be the unmarked form, while "gdyż" brings various connotations (serious, a bit antiquated, etc.).

**Comment by splewako** [comment]
Let's leave it as it is now then.
