### ISSUE TITLE
Correct declension of "iOS"

### ISSUE THREAD

**Issue by piotrdrag** [aviarypl/team#7]
As I mentioned some time ago, and Bartosz brought up on team@, the currently used declension of "iOS" is wrong. It is an acronym ("iOS" → "iPhone OS" → "iPhone Operating System") and should be declined as such, with a hyphen (e.g. "iOS-a").

Resource listed by Bartosz: http://wittamina.pl/apostrof-w-zlym-miejscu/

**Comment by splewako** [comment]
In my opinion it is not an acronym. The system was indeed originally named "iPhone OS" (somehow accidentally IIRC and initially even Mac OS X) but later it was **renamed** to iOS to reflect that it isn't exclusive to iPhone but also used on iPad (first original target) and iPod.

In other words, "i" in "iOS" doesn't stand for iPhone but it's a naming convention used by the Apple for multiple products and services (started probably with iMac in 1998).

**Comment by piotrdrag** [comment]
I don't believe that the fact that "i" doesn't stand for iPhone (and you could argue that it stands for iPhone, iPad and iPod at the same time) matters in this issue. The word functions as an acronym in the Polish language.

I asked a friend with an MA in Polish and she agrees that it is an acronym, and "iOSa" is incorrect.

Another resource, by the way: https://mobirank.pl/2015/02/21/jezyk-polski-a-nowa-technologia/

**Comment by zbraniecki** [comment]
The last link convinces me. I'm voting for "iOS-a".

**Comment by splewako** [comment]
> I don't believe that the fact that "i" doesn't stand for iPhone (and you could argue that it stands for iPhone, iPad and iPod at the same time) matters in this issue.

If doesn't (not formed as an abbreviation) then for me it means that this is a proper name not an [acronym](https://en.wikipedia.org/wiki/Acronym).

> The word functions as an acronym in the Polish language.
> 
> I asked a friend with an MA in Polish and she agrees that it is an acronym, and "iOSa" is incorrect.
> 
> Another resource, by the way: https://mobirank.pl/2015/02/21/jezyk-polski-a-nowa-technologia/

I can understand why people may think that this is acronym (assumption drown from strange marketing spelling and/or not knowing Apple history) but repeating statements and opinions without arguments is not very helpful, this is not a contest.

**Comment by bpiec** [comment]
> I can understand why people may think that this is acronym (assumption drown from strange marketing spelling and/or not knowing Apple history) but repeating statements and opinions without arguments is not very helpful, this is not a contest.

Where your arguments then?

**Comment by piotrdrag** [comment]
> If doesn't (not formed as an abbreviation) then for me it means that this is a proper name not an acronym.

An acronym can't be a proper name?

**Comment by splewako** [comment]
> Where your arguments then?

Read the discussion from the beginning if you want to find some.

> If doesn't (not formed as an abbreviation) then for me it means that this is a proper name not an acronym.
> 
> An acronym can't be a proper name?

I don't think that a name not formed as an abbreviation could be considered as an acronym.

**Comment by splewako** [comment]
Apple operating system for iPhones, iPads and iPods once named "iPhone OS" was in 2010 renamed to "iOS". See https://en.wikipedia.org/wiki/IOS#History for more information.

I don't see nothing convincing here that the system is still named "iPhone OS" and therefore "iOS" is an acronym of it or that "iOS" is acronym at all.

Renaming doesn't [form acronyms](https://en.wikipedia.org/wiki/Acronym) and taking into account other Apple product names it seems to be coincidence that it looks (more than other) like one.

Therefore correct declination is **iOSa**.

**Comment by stasm** [comment]
(For the sake of consistency I'm writing this in English but I wish that my strong preference towards having these discussions in Polish be heard.)

My last name is technically a noun but is declined as if it were an adjective.  Since it's a proper name, it's up to me to choose how I want it to be declined. My family chose to decline as an adjective. We could have chosen to decline it as a noun.  It would be confusing to people and not very helpful. Consider: _Nie ma Stasia Małolepszego_ vs. _Nie ma Stasia Małolepsza_.

Languages are weird that way. The main take-away from this thread is that it's secondary whether _iOS_ is an acronym or not. To your point, it can be something else — but still be declined as an acronym. We should either ask Apple for their preference or go with something that isn't surprising to people.

**Comment by piotrdrag** [comment]
(Czuj się wolny pisać po polsku :) )

**Comment by splewako** [comment]
I'm not entirely convinced that owners should have totally free hand in deciding how names should be declined (like "iOS'u") but in this case it is only Apple decision whenever iOS is an acronym or not (and "iOSa" vs "iOS-a").

Apple statement could clarify this, please include community-poland@ in such discussion.
