### ISSUE TITLE
Decide on how to translate "Activity Stream"

### ISSUE THREAD

**Issue by piotrdrag** [aviarypl/team#8]
First commit with the new feature arrived in mobile: https://hg.mozilla.org/mozilla-central/diff/9aa406751838/mobile/android/base/locales/en-US/android_strings.dtd

**Comment by splewako** [comment]
I would leave it untranslated (as a name) for now I guess, hoping that the term won't be used in UI after test phase.

**Comment by piotrdrag** [comment]
Let's worry about it later, then.
